[package]
name = "system-logs-diagnostic"
version = "0.1.0-beta"
edition = "2021"
authors = ["Marcel Stevano"]
license = "GPL-3.0-or-later"

[dependencies]
gtk = { package = "gtk4", version = "0.9", features = ["v4_12"] }
adw = { package = "libadwaita", version = "0.7", features = ["v1_6"] }

glib = "0.20"
gio = "0.20"

regex = "1"

